# Generated by Django 3.0.14 on 2022-04-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0003_vehicule_typecarburant'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='EndTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='StartTime',
            field=models.TimeField(null=True),
        ),
    ]
