# Generated by Django 3.0.14 on 2022-04-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0004_auto_20220421_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='EndTime',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='StartTime',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='dateDebut',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='dateFin',
        ),
        migrations.AddField(
            model_name='mission',
            name='EndMiss',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='StartMiss',
            field=models.DateTimeField(null=True),
        ),
    ]
