# Generated by Django 3.0.14 on 2022-04-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0005_auto_20220421_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='permis',
        ),
        migrations.AddField(
            model_name='employe',
            name='NumPermis',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='category_Permis',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='date_EXP_Permis',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='dispo',
            field=models.BooleanField(null=True),
        ),
    ]
