# Generated by Django 3.0.14 on 2022-05-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0006_auto_20220426_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='dispo',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='disponible',
        ),
        migrations.AddField(
            model_name='employe',
            name='disponibilite',
            field=models.CharField(choices=[('Dispo', 'Dispo'), ('DuringMiss', 'DuringMiss'), ('NonDispo', 'NonDispo')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='Availability',
            field=models.CharField(choices=[('Dispo', 'Dispo'), ('DuringMiss', 'DuringMiss'), ('enPanne', 'enPanne')], max_length=20, null=True),
        ),
    ]
