# Generated by Django 3.0.14 on 2022-05-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0008_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
