# Generated by Django 3.0.14 on 2022-05-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0009_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='Status',
            field=models.CharField(choices=[('Aprov', 'Aprov'), ('Reject', 'Reject')], max_length=20, null=True),
        ),
    ]
