# Generated by Django 3.0.14 on 2022-05-27 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0011_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_Location', models.CharField(choices=[('Achat', 'Achat'), ('Rent', 'Rent'), ('Credit', 'Credit')], max_length=20, null=True)),
                ('Start_Location', models.DateTimeField(null=True)),
                ('End_Location', models.DateTimeField(null=True)),
                ('prix', models.IntegerField(null=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.vehicule')),
            ],
        ),
    ]
