# Generated by Django 3.0.14 on 2022-05-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0012_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='prix',
        ),
    ]
