# Generated by Django 3.0.14 on 2022-05-27 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0014_reparations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reparations',
            new_name='Reparation',
        ),
    ]
