# Generated by Django 3.0.14 on 2022-06-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0015_auto_20220527_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparation',
            name='Facture',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reparation',
            name='type_Panne',
            field=models.CharField(choices=[('vidange', 'vidange'), ('batterie', ' batterie'), ('fuite du joint de culasse', 'fuite du joint de culasse'), (' l’huile moteur', ' l’huile moteur'), (' liquide de refroidissement', ' liquide de refroidissement')], max_length=100, null=True),
        ),
    ]
